# -*- coding: utf-8 -*-
"""EXP7MLDL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EntBzZp3vVAynxJNwsCZeeyupstsNMkD
"""

# -------------------------------
# 1. Install & Import Libraries
# -------------------------------
!pip install tensorflow

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# -------------------------------
# 2. Upload Dataset
# -------------------------------
from google.colab import files
uploaded = files.upload()

# Load dataset
df = pd.read_csv('calories.csv')

print("Dataset Preview:")
print(df.head())

# -------------------------------
# 3. Data Preprocessing
# -------------------------------

# Convert categorical column (Gender)
df = pd.get_dummies(df, drop_first=True)

# Split features and target
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

# -------------------------------
# 4. Train-Test Split
# -------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# -------------------------------
# 5. Feature Scaling
# -------------------------------
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# -------------------------------
# 6. Build ANN Model
# -------------------------------
model = Sequential()

model.add(Dense(16, activation='relu', input_dim=X_train.shape[1]))
model.add(Dense(8, activation='relu'))
model.add(Dense(1))  # Output layer

# Compile model
model.compile(
    optimizer='adam',
    loss='mean_squared_error',
    metrics=['mae']
)

# -------------------------------
# 7. Train Model
# -------------------------------
history = model.fit(
    X_train,
    y_train,
    epochs=50,
    batch_size=16,
    validation_split=0.2,
    verbose=1
)

# -------------------------------
# 8. Predictions
# -------------------------------
y_pred = model.predict(X_test).flatten()

# -------------------------------
# 9. Visualization 1: Loss Curve
# -------------------------------
plt.figure()
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title("Training vs Validation Loss")
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.legend(["Train Loss", "Validation Loss"])
plt.show()

# -------------------------------
# 10. Visualization 2: Actual vs Predicted
# -------------------------------
plt.figure()
plt.scatter(y_test, y_pred)
plt.title("Actual vs Predicted")
plt.xlabel("Actual Values")
plt.ylabel("Predicted Values")
plt.show()

# -------------------------------
# 11. Visualization 3: Residual Plot
# -------------------------------
residuals = y_test - y_pred

plt.figure()
plt.scatter(y_pred, residuals)
plt.title("Residual Plot")
plt.xlabel("Predicted Values")
plt.ylabel("Residuals")
plt.show()

# -------------------------------
# 12. Performance (R² Score)
# -------------------------------
r2 = r2_score(y_test, y_pred)
print("R² Score:", r2)