# -*- coding: utf-8 -*-
"""MLDL EXP1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k1UekzneqX57dkXN_8wXCym4tMP-Ab0p
"""

# IMPORT LIBRARIES

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import files

# 1. Load CSV file using Pandas

print("📂 Upload student_performance.csv")
uploaded = files.upload()

df = pd.read_csv(list(uploaded.keys())[0])

# 2. Check shape, columns, and missing values
print("\nDataset Shape:", df.shape)
print("\nColumns in Dataset:")
print(df.columns)

print("\nMissing Values:")
print(df.isnull().sum())

# 3. Create Performance label based on Final_Score
def performance_label(score):
    if score < 50:
        return "Low Performance"
    elif score < 75:
        return "Medium Performance"
    else:
        return "High Performance"

df['Performance_Label'] = df['Final_Score'].apply(performance_label)

print("\nPerformance Label Column Added:")
print(df[['Final_Score', 'Performance_Label']].head())


# EXERCISE 1: NUMPY BASICS

# 1. Load Final_Score as NumPy array
final_score_np = df['Final_Score'].to_numpy()

print("\nFinal_Score as NumPy Array (Sample):")
print(final_score_np[:10])

# 2. Mean, Median, Standard Deviation
print("\nMean of Final_Score:", np.mean(final_score_np))
print("Median of Final_Score:", np.median(final_score_np))
print("Standard Deviation of Final_Score:", np.std(final_score_np))

# 3. Min-Max Normalization
min_val = final_score_np.min()
max_val = final_score_np.max()
normalized_scores = (final_score_np - min_val) / (max_val - min_val)

print("\nMin-Max Normalized Final_Score (Sample):")
print(normalized_scores[:10])

# EXERCISE 3: MATPLOTLIB VISUALIZATION

# 1. Line plot: Hours_Studied vs Final_Score
plt.figure()
plt.plot(df['Hours_Studied'], df['Final_Score'])
plt.xlabel("Hours Studied")
plt.ylabel("Final Score")
plt.title("Hours Studied vs Final Score (Line Plot)")
plt.show()

# 2. Histogram of Final_Score
plt.figure()
plt.hist(df['Final_Score'], bins=20)
plt.xlabel("Final Score")
plt.ylabel("Frequency")
plt.title("Histogram of Final Score")
plt.show()

# EXERCISE 4: SEABORN VISUALIZATION

# 1. Scatter plot
plt.figure()
sns.scatterplot(x='Hours_Studied', y='Final_Score', data=df)
plt.title("Scatter Plot: Hours Studied vs Final Score")
plt.show()

# 2. Heatmap for correlation analysis
plt.figure(figsize=(8,6))
sns.heatmap(df[['Hours_Studied', 'Attendance',
                'Assignment_Score', 'Midterm_Score',
                'Final_Score']].corr(),
            annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

# 3. Boxplot for categorical analysis
plt.figure()
sns.boxplot(x='Performance_Label', y='Final_Score', data=df)
plt.title("Final Score by Performance Category")
plt.show()

print("\n✅ All exercises completed successfully")