# -*- coding: utf-8 -*-
"""MLDLEXP5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jWNKJM1SdZ3zRGkd3jMFYLtNYVQEQGNh
"""

# ---------------------------------------------
# STEP 1: Upload Dataset (FOR COLAB)
# ---------------------------------------------
from google.colab import files
uploaded = files.upload()

# ---------------------------------------------
# STEP 2: Import Libraries
# ---------------------------------------------
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# ---------------------------------------------
# STEP 3: Load Dataset
# ---------------------------------------------
file_name = list(uploaded.keys())[0]
df = pd.read_csv(file_name)

print("✅ Dataset Loaded Successfully")
print(df.head())

# ---------------------------------------------
# STEP 4: Clean Column Names
# ---------------------------------------------
df.columns = df.columns.str.strip()
print("\nColumns:", df.columns)

# ---------------------------------------------
# STEP 5: Encode Gender
# ---------------------------------------------
df['Gender'] = LabelEncoder().fit_transform(df['Gender'])

# ---------------------------------------------
# STEP 6: Convert Calories to Classification
# ---------------------------------------------
median_val = df['Calories'].median()
df['Calories_Class'] = np.where(df['Calories'] > median_val, 1, 0)

# ---------------------------------------------
# 🔥 Visualization 1: Class Distribution
# ---------------------------------------------
plt.figure()
df['Calories_Class'].value_counts().plot(kind='bar')
plt.title("Class Distribution (0 = Low, 1 = High)")
plt.xlabel("Class")
plt.ylabel("Count")
plt.show()

# ---------------------------------------------
# STEP 7: Drop Unnecessary Columns
# ---------------------------------------------
if 'User_ID' in df.columns:
    df.drop('User_ID', axis=1, inplace=True)

df.drop('Calories', axis=1, inplace=True)

# ---------------------------------------------
# STEP 8: Features & Target
# ---------------------------------------------
X = df.drop('Calories_Class', axis=1)
y = df['Calories_Class']

# ---------------------------------------------
# STEP 9: Train-Test Split
# ---------------------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# ---------------------------------------------
# STEP 10: Feature Scaling
# ---------------------------------------------
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# ---------------------------------------------
# STEP 11: SVM Model
# ---------------------------------------------
svm = SVC()

# ---------------------------------------------
# STEP 12: Hyperparameter Tuning
# ---------------------------------------------
param_grid = {
    'C': [0.1, 1, 10],
    'kernel': ['linear', 'rbf'],
    'gamma': ['scale', 'auto']
}

grid = GridSearchCV(svm, param_grid, cv=5, scoring='accuracy')
grid.fit(X_train, y_train)

# ---------------------------------------------
# STEP 13: Best Parameters
# ---------------------------------------------
print("\n✅ Best Parameters:", grid.best_params_)

# ---------------------------------------------
# STEP 14: Prediction
# ---------------------------------------------
best_model = grid.best_estimator_
y_pred = best_model.predict(X_test)

# ---------------------------------------------
# STEP 15: Evaluation
# ---------------------------------------------
acc = accuracy_score(y_test, y_pred)
print("\n✅ Accuracy: {:.2f}%".format(acc * 100))

print("\nConfusion Matrix:")
cm = confusion_matrix(y_test, y_pred)
print(cm)

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# ---------------------------------------------
# 🔥 Visualization 2: Confusion Matrix Heatmap
# ---------------------------------------------
plt.figure()
sns.heatmap(cm, annot=True, fmt='d')
plt.title("Confusion Matrix Heatmap")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()