# -*- coding: utf-8 -*-
"""MLDLEXP1.1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qG-nX2mxaZn16CqtlRmtdneugUf6fFgl
"""

# Upload CSV file
from google.colab import files
uploaded = files.upload()

# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.metrics import mean_squared_error, accuracy_score

# Load dataset
file_name = list(uploaded.keys())[0]
df = pd.read_csv(file_name)

# Clean column names
df.columns = df.columns.str.strip()

# Convert categorical data to numeric
if 'Gender' in df.columns:
    df['Gender'] = df['Gender'].map({'male': 1, 'female': 0})

df = pd.get_dummies(df, drop_first=True)

print("Dataset Loaded Successfully")
print(df.head())

# 1️⃣ CORRELATION HEATMAP

plt.figure(figsize=(8,6))
sns.heatmap(df.corr(), annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

# LINEAR REGRESSION

X = df.iloc[:, :-1]
y = df.iloc[:, -1]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

linear_model = LinearRegression()
linear_model.fit(X_train, y_train)

y_pred = linear_model.predict(X_test)

print("\nLINEAR REGRESSION")
print("Mean Squared Error:", mean_squared_error(y_test, y_pred))

# 2️⃣ SCATTER PLOT (Actual vs Predicted)

plt.figure()
plt.scatter(y_test, y_pred)
plt.xlabel("Actual Values")
plt.ylabel("Predicted Values")
plt.title("Scatter Plot: Actual vs Predicted")
plt.show()

# 3️⃣ LINE PLOT (Actual & Predicted)

plt.figure()
plt.plot(range(len(y_test)), y_test.values, label="Actual Values")
plt.plot(range(len(y_pred)), y_pred, label="Predicted Values")
plt.xlabel("Test Data Index")
plt.ylabel("Calories")
plt.title("Line Plot: Actual vs Predicted")
plt.legend()
plt.show()

# 4️⃣ BOX PLOT (Calories Distribution)

plt.figure()
sns.boxplot(y=y)
plt.title("Box Plot of Calories")
plt.ylabel("Calories")
plt.show()

# LOGISTIC REGRESSION

y_binary = np.where(y > y.mean(), 1, 0)

X_train, X_test, y_train, y_test = train_test_split(
    X, y_binary, test_size=0.2, random_state=42
)

logistic_model = LogisticRegression(max_iter=1000)
logistic_model.fit(X_train, y_train)

y_pred = logistic_model.predict(X_test)

print("\nLOGISTIC REGRESSION")
print("Accuracy:", accuracy_score(y_test, y_pred))

print("\n✅ Experiment Completed Successfully")