# -*- coding: utf-8 -*-
"""MLDLEXP6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i4upCxzhxQqwYwQ1ahMu52MJz4B7s5h3
"""



import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans, AgglomerativeClustering
from scipy.cluster.hierarchy import dendrogram, linkage

# Load the dataset
df = pd.read_csv('/content/calories.csv')

print("Original DataFrame head:")
display(df.head())
print("\nDataFrame Info:")
df.info()

"""The dataset contains columns like 'User_ID', 'Gender', 'Age', 'Height', 'Weight', 'Duration', 'Heart_Rate', 'Body_Temp', 'Calories'.

For clustering, 'User_ID' and 'Gender' are not directly suitable. 'Gender' is categorical and would need one-hot encoding if we wanted to include it, but for a first pass, we can focus on numerical features that directly relate to physical attributes and activity.

Let's select the numerical columns related to physical characteristics and activity for clustering: 'Age', 'Height', 'Weight', 'Duration', 'Heart_Rate', 'Body_Temp', 'Calories'.

We will also check for and handle any missing values, and then scale the data, which is crucial for distance-based clustering algorithms like K-Means and Hierarchical Clustering.
"""

# Select numerical features for clustering
features = ['Age', 'Height', 'Weight', 'Duration', 'Heart_Rate', 'Body_Temp', 'Calories']
X = df[features].copy()

# Check for missing values
print("Missing values before handling:")
display(X.isnull().sum())

# For simplicity, we will fill any missing numerical values with the mean of their respective columns.
# In a real-world scenario, more sophisticated imputation methods might be considered.
X.fillna(X.mean(), inplace=True)

print("\nMissing values after handling:")
display(X.isnull().sum())

# Scale the data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

print("\nScaled data head (first 5 rows and columns):")
display(pd.DataFrame(X_scaled, columns=features).head())

# Elbow Method to find optimal k for K-Means
wcss = []
for i in range(1, 11):
    kmeans = KMeans(n_clusters=i, init='k-means++', random_state=42, n_init=10)
    kmeans.fit(X_scaled)
    wcss.append(kmeans.inertia_)

fig = plt.figure(figsize=(10, 6))
plt.plot(range(1, 11), wcss, marker='o')
plt.title('Elbow Method for K-Means')
plt.xlabel('Number of clusters (k)')
plt.ylabel('WCSS')
plt.grid(True)
plt.show()

"""Based on the Elbow method, let's choose `k=3` for K-Means clustering. Now, we'll apply K-Means with 3 clusters and visualize the results."""

# Apply K-Means clustering with k=3
kmeans_model = KMeans(n_clusters=3, init='k-means++', random_state=42, n_init=10)
df['KMeans_Cluster'] = kmeans_model.fit_predict(X_scaled)

print("K-Means Cluster distribution:")
display(df['KMeans_Cluster'].value_counts())

# Visualize K-Means clusters (using first two principal components or any two features for simplicity)
# For a more robust visualization in higher dimensions, dimensionality reduction techniques like PCA are often used.

# Let's visualize using 'Age' and 'Calories' as an example
fig = plt.figure(figsize=(10, 7))
sns.scatterplot(x='Age', y='Calories', hue='KMeans_Cluster', data=df, palette='viridis', s=100, alpha=0.7)
plt.title('K-Means Clustering: Age vs Calories')
plt.xlabel('Age')
plt.ylabel('Calories Burned')
plt.grid(True)
plt.show()

# Another visualization using 'Duration' and 'Heart_Rate'
fig = plt.figure(figsize=(10, 7))
sns.scatterplot(x='Duration', y='Heart_Rate', hue='KMeans_Cluster', data=df, palette='viridis', s=100, alpha=0.7)
plt.title('K-Means Clustering: Duration vs Heart Rate')
plt.xlabel('Duration (minutes)')
plt.ylabel('Heart Rate')
plt.grid(True)
plt.show()

"""Next, let's perform Hierarchical Clustering on the same scaled dataset. We'll start by generating a dendrogram to help determine the optimal number of clusters, and then apply Agglomerative Clustering."""

# Hierarchical Clustering - Create Dendrogram
# Using 'ward' linkage minimizes the variance within each cluster.
linked = linkage(X_scaled, method='ward')

fig = plt.figure(figsize=(15, 8))
dendrogram(linked,
           orientation='top',
           distance_sort='descending',
           show_leaf_counts=True)
plt.title('Dendrogram for Hierarchical Clustering')
plt.xlabel('Sample Index')
plt.ylabel('Distance')
plt.show()

# Based on the dendrogram, we can choose a number of clusters.
# For example, cutting the dendrogram at a certain height to get, say, 3 clusters.

# Apply Agglomerative Clustering with 3 clusters
hierarchical_model = AgglomerativeClustering(n_clusters=3, metric='euclidean', linkage='ward')
df['Hierarchical_Cluster'] = hierarchical_model.fit_predict(X_scaled)

print("Hierarchical Cluster distribution:")
display(df['Hierarchical_Cluster'].value_counts())

# Visualize Hierarchical clusters (using 'Age' and 'Calories' as an example)
fig = plt.figure(figsize=(10, 7))
sns.scatterplot(x='Age', y='Calories', hue='Hierarchical_Cluster', data=df, palette='viridis', s=100, alpha=0.7)
plt.title('Hierarchical Clustering: Age vs Calories')
plt.xlabel('Age')
plt.ylabel('Calories Burned')
plt.grid(True)
plt.show()

# Another visualization using 'Duration' and 'Heart_Rate'
fig = plt.figure(figsize=(10, 7))
sns.scatterplot(x='Duration', y='Heart_Rate', hue='Hierarchical_Cluster', data=df, palette='viridis', s=100, alpha=0.7)
plt.title('Hierarchical Clustering: Duration vs Heart Rate')
plt.xlabel('Duration (minutes)')
plt.ylabel('Heart Rate')
plt.grid(True)
plt.show()

"""```text
Hierarchical Cluster distribution:
```



| Hierarchical_Cluster | count | Dtype |
| :------------------- | :---- | :---- |
| 0                    | 6817  |       |
| 1                    | 4573  |       |
| 2                    | 3610  |       |




```text
<Figure size 1000x700 with 1 Axes>
```




```text
<Figure size 1000x700 with 1 Axes>
```

Based on the dendrogram, let's choose 3 clusters for Hierarchical Clustering as well. We'll use `AgglomerativeClustering` and visualize the results similar to K-Means.
"""

# Apply Agglomerative Clustering with 3 clusters
hierarchical_model = AgglomerativeClustering(n_clusters=3, metric='euclidean', linkage='ward')
df['Hierarchical_Cluster'] = hierarchical_model.fit_predict(X_scaled)

print("Hierarchical Cluster distribution:")
display(df['Hierarchical_Cluster'].value_counts())

# Visualize Hierarchical clusters (using 'Age' and 'Calories' as an example)
fig = plt.figure(figsize=(10, 7))
sns.scatterplot(x='Age', y='Calories', hue='Hierarchical_Cluster', data=df, palette='viridis', s=100, alpha=0.7)
plt.title('Hierarchical Clustering: Age vs Calories')
plt.xlabel('Age')
plt.ylabel('Calories Burned')
plt.grid(True)
plt.show()

# Another visualization using 'Duration' and 'Heart_Rate'
fig = plt.figure(figsize=(10, 7))
sns.scatterplot(x='Duration', y='Heart_Rate', hue='Hierarchical_Cluster', data=df, palette='viridis', s=100, alpha=0.7)
plt.title('Hierarchical Clustering: Duration vs Heart Rate')
plt.xlabel('Duration (minutes)')
plt.ylabel('Heart Rate')
plt.grid(True)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans, AgglomerativeClustering
from scipy.cluster.hierarchy import dendrogram, linkage

# --- 1. Data Loading and Initial Inspection ---
print("--- Data Loading and Initial Inspection ---")
df = pd.read_csv('/content/calories.csv')
print("Original DataFrame head:")
display(df.head())
print("\nDataFrame Info:")
df.info()

# --- 2. Feature Selection and Preprocessing ---
print("\n--- Feature Selection and Preprocessing ---")
features = ['Age', 'Height', 'Weight', 'Duration', 'Heart_Rate', 'Body_Temp', 'Calories']
X = df[features].copy()

print("Missing values before handling:")
display(X.isnull().sum())
X.fillna(X.mean(), inplace=True)
print("\nMissing values after handling:")
display(X.isnull().sum())

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print("\nScaled data head (first 5 rows and columns):")
display(pd.DataFrame(X_scaled, columns=features).head())

# --- 3. K-Means Clustering ---
print("\n--- K-Means Clustering ---")
# Elbow Method to find optimal k for K-Means
wcss = []
for i in range(1, 11):
    kmeans = KMeans(n_clusters=i, init='k-means++', random_state=42, n_init=10)
    kmeans.fit(X_scaled)
    wcss.append(kmeans.inertia_)

fig = plt.figure(figsize=(10, 6))
plt.plot(range(1, 11), wcss, marker='o')
plt.title('Elbow Method for K-Means')
plt.xlabel('Number of clusters (k)')
plt.ylabel('WCSS')
plt.grid(True)
plt.show()

# Apply K-Means clustering with k=3 (based on elbow method observation)
kmeans_model = KMeans(n_clusters=3, init='k-means++', random_state=42, n_init=10)
df['KMeans_Cluster'] = kmeans_model.fit_predict(X_scaled)

print("\nK-Means Cluster distribution (k=3):")
display(df['KMeans_Cluster'].value_counts())

# Visualize K-Means clusters
fig = plt.figure(figsize=(10, 7))
sns.scatterplot(x='Age', y='Calories', hue='KMeans_Cluster', data=df, palette='viridis', s=100, alpha=0.7)
plt.title('K-Means Clustering: Age vs Calories')
plt.xlabel('Age')
plt.ylabel('Calories Burned')
plt.grid(True)
plt.show()

fig = plt.figure(figsize=(10, 7))
sns.scatterplot(x='Duration', y='Heart_Rate', hue='KMeans_Cluster', data=df, palette='viridis', s=100, alpha=0.7)
plt.title('K-Means Clustering: Duration vs Heart Rate')
plt.xlabel('Duration (minutes)')
plt.ylabel('Heart Rate')
plt.grid(True)
plt.show()

# --- 4. Hierarchical Clustering ---
print("\n--- Hierarchical Clustering ---")
# Create Dendrogram to determine optimal number of clusters
linked = linkage(X_scaled, method='ward')

fig = plt.figure(figsize=(15, 8))
dendrogram(linked,
           orientation='top',
           distance_sort='descending',
           show_leaf_counts=True)
plt.title('Dendrogram for Hierarchical Clustering')
plt.xlabel('Sample Index')
plt.ylabel('Distance')
plt.show()

# Apply Agglomerative Clustering with 3 clusters (based on dendrogram observation)
hierarchical_model = AgglomerativeClustering(n_clusters=3, metric='euclidean', linkage='ward')
df['Hierarchical_Cluster'] = hierarchical_model.fit_predict(X_scaled)

print("\nHierarchical Cluster distribution (k=3):")
display(df['Hierarchical_Cluster'].value_counts())

# Visualize Hierarchical clusters
fig = plt.figure(figsize=(10, 7))
sns.scatterplot(x='Age', y='Calories', hue='Hierarchical_Cluster', data=df, palette='viridis', s=100, alpha=0.7)
plt.title('Hierarchical Clustering: Age vs Calories')
plt.xlabel('Age')
plt.ylabel('Calories Burned')
plt.grid(True)
plt.show()

fig = plt.figure(figsize=(10, 7))
sns.scatterplot(x='Duration', y='Heart_Rate', hue='Hierarchical_Cluster', data=df, palette='viridis', s=100, alpha=0.7)
plt.title('Hierarchical Clustering: Duration vs Heart Rate')
plt.xlabel('Duration (minutes)')
plt.ylabel('Heart Rate')
plt.grid(True)
plt.show()