# -*- coding: utf-8 -*-
"""EXP 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mc3zii0ED5-7r-60vf9IKiJDXsSYfYEI
"""

# K-Nearest Neighbors (KNN) Classification
# Dataset: calories.csv

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler, LabelEncoder

# 1️⃣ Load Dataset
df = pd.read_csv("calories.csv")

print("First 5 Rows:")
print(df.head())

# 2️⃣ Data Preprocessing

# Drop User_ID if present
if 'User_ID' in df.columns:
    df = df.drop('User_ID', axis=1)

# 🔹 Encode Gender column (male/female → 0/1)
if 'Gender' in df.columns:
    le = LabelEncoder()
    df['Gender'] = le.fit_transform(df['Gender'])

# Convert Calories into classification problem
threshold = df['Calories'].median()
df['Calories_Class'] = np.where(df['Calories'] > threshold, 1, 0)

# Define Features and Target
X = df.drop(['Calories', 'Calories_Class'], axis=1)
y = df['Calories_Class']

# 3️⃣ Feature Scaling
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# 4️⃣ Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

# 5️⃣ Apply KNN
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

# 6️⃣ Predictions
y_pred = knn.predict(X_test)

# 7️⃣ Evaluation
accuracy = accuracy_score(y_test, y_pred)

print("\nModel Accuracy:", accuracy)
print("\nClassification Report:\n", classification_report(y_test, y_pred))

# 📊 Visualization 1: Confusion Matrix

cm = confusion_matrix(y_test, y_pred)

plt.figure()
sns.heatmap(cm, annot=True, fmt='d')
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

# 📊 Visualization 2: Accuracy vs K Value

k_values = range(1, 21)
accuracy_list = []

for k in k_values:
    model = KNeighborsClassifier(n_neighbors=k)
    model.fit(X_train, y_train)
    pred = model.predict(X_test)
    accuracy_list.append(accuracy_score(y_test, pred))

plt.figure()
plt.plot(k_values, accuracy_list)
plt.title("Accuracy vs K Value")
plt.xlabel("K Value")
plt.ylabel("Accuracy")
plt.show()