# -*- coding: utf-8 -*-
"""EXP3 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-bMNAgF31JwAkRLviqWvtgPxTzW42O7F
"""

# ============================================
# Decision Tree & Random Forest Classification
# Dataset: insurance.csv
# ============================================

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import LabelEncoder

# 1️⃣ Load Dataset
df = pd.read_csv("insurance.csv")

print("First 5 Rows:")
print(df.head())

print("\nDataset Shape:", df.shape)
print("\nColumn Names:", df.columns)

# 2️⃣ Convert categorical columns into numeric
for col in df.columns:
    if df[col].dtype == 'object':
        le = LabelEncoder()
        df[col] = le.fit_transform(df[col])

# 3️⃣ Convert LAST column into classification categories
# (because insurance dataset has continuous values)

target_column = df.columns[-1]

df['target_category'] = pd.qcut(df[target_column],
                                 q=3,
                                 labels=[0,1,2])

# 4️⃣ Define Features and Target
X = df.drop([target_column, 'target_category'], axis=1)
y = df['target_category']

# 5️⃣ Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

# ============================================
# 6️⃣ Decision Tree
# ============================================

dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, y_train)

dt_pred = dt_model.predict(X_test)

dt_accuracy = accuracy_score(y_test, dt_pred)

print("\n===== Decision Tree =====")
print("Accuracy:", dt_accuracy)
print(classification_report(y_test, dt_pred))


# ============================================
# 7️⃣ Random Forest
# ============================================

rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train, y_train)

rf_pred = rf_model.predict(X_test)

rf_accuracy = accuracy_score(y_test, rf_pred)

print("\n===== Random Forest =====")
print("Accuracy:", rf_accuracy)
print(classification_report(y_test, rf_pred))


# ============================================
# 8️⃣ Bar Chart - Accuracy Comparison
# ============================================

plt.figure()
plt.bar(["Decision Tree", "Random Forest"],
        [dt_accuracy, rf_accuracy])
plt.title("Model Accuracy Comparison")
plt.xlabel("Model")
plt.ylabel("Accuracy")
plt.show()


# ============================================
# 9️⃣ Histogram - BMI Distribution (example feature)
# ============================================

plt.figure()
plt.hist(df[df.columns[2]], bins=20)
plt.title("Histogram of Feature")
plt.xlabel("Value")
plt.ylabel("Frequency")
plt.show()


# ============================================
# 🔟 Correlation Heatmap
# ============================================

plt.figure()

correlation_matrix = df.drop('target_category', axis=1).corr()
plt.imshow(correlation_matrix)

plt.title("Correlation Heatmap")
plt.xticks(range(len(correlation_matrix.columns)),
           correlation_matrix.columns,
           rotation=90)

plt.yticks(range(len(correlation_matrix.columns)),
           correlation_matrix.columns)

plt.colorbar()
plt.show()

print("\nExperiment Completed Successfully!")